import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { Post } from 'src/app/models';
import { ApiService } from 'src/app/services/api.service';

@Component({
  selector: 'app-dialog-create',
  templateUrl: './dialog-create.component.html',
  styleUrls: ['./dialog-create.component.scss'],
})
export class DialogCreateComponent {
  formGroup = this.fb.group({
    title: ['', Validators.required],
    content: ['', Validators.required],
    lat: ['', Validators.required],
    long: ['', Validators.required],
    image_url: ['', Validators.required],
  });
  constructor(
    private fb: FormBuilder,
    public apiService: ApiService,
    public dialog: MatDialog
  ) {}

  onSubmit(post: Post) {
    //keys id, created_at and updated_at are auto generated by the api server.
    this.apiService.createNewPost(post);
    this.dialog.closeAll();
  }
}
